# Workflow는 CI를 실행하기 위한 스크립트의 모음
# 자동화된 전체 프로세스로 하나 이상의 job으로 구성됨

# Workflow의 이름
name: CI

# event : workflow를 동작하게하는 trigger
# Workflow가 시작될 조건 지정 (main 브랜치에 푸시를 할 때마다 workflow를 시작하도록 작성)
on:
  push:
    branches: [ main ]

# job은 사용자가 정한 플랫폼을 통해 step이라는 일련의 과정을 실행할 수 있다.
# 여러 개의 job을 사용할 수 있으며, 여러 개의 job을 사용할 때는 서로 정보도 교환할 수 있다.
# 그리고 각각 독립적으로도 실행할 수도 있다.
jobs:
  build:
    runs-on: ubuntu-latest # 실행 환경 지정 (job의 필수 속성)
    # step : job에서 커맨드를 실행하는 독립적인 단위 (job의 필수 속성)
    # 실행 스텝 지정
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.AUTH_TOKEN }}
          submodules: true

      # uses 키워드는 지정한 리포지토리를 확인하고 코드에 대한 작업을 실행할 수 있다.
      # action/checkout 에는 checkout이라는 작업의 v3 버전을 실행합니다.
      - uses : actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      # name : 스텝의 이름
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # run : 실행할 명령어
      - name: Build with Gradle
        run: ./gradlew clean build

